#!/usr/bin/env node
// Per-tier coverage gate (spec §10.3 / criterion #5).
//
// Walks every corpus test in test/corpus/*.txt, parses the M source with
// the tree-sitter-m grammar, collects every keyword node's (node_type,
// matched_text), joins via lib/stamp.js to its (concept, canonical,
// standard_status) triple, and verifies every triple in
// src/grammar-metadata.json is covered by at least one test.
//
// Fails (exit 1) with a diff list if any triple is uncovered. CI runs
// this as part of the `grammar` job so a new keyword added to
// m-standard's grammar-surface.json without a corresponding corpus test
// breaks the build.
//
// Usage:
//   node tools/coverage-gate.js
//   node tools/coverage-gate.js --json    # machine-readable diff output

'use strict';

const fs = require('fs');
const path = require('path');

const Parser = require('tree-sitter');
const M = require('..');
const stamp = require('../lib/stamp');

const PROJECT_ROOT = path.resolve(__dirname, '..');
const CORPUS_DIR = path.join(PROJECT_ROOT, 'test', 'corpus');
const COVERAGE_DIR = path.join(PROJECT_ROOT, 'test', 'coverage');
const METADATA_PATH = path.join(PROJECT_ROOT, 'src', 'grammar-metadata.json');

const args = process.argv.slice(2);
const asJson = args.includes('--json');

// --- collect required (concept, canonical, status) triples --------------------

function loadRequiredTriples() {
  const md = JSON.parse(fs.readFileSync(METADATA_PATH, 'utf-8')).metadata;
  const triples = new Set();
  for (const key of Object.keys(md)) {
    for (const e of md[key]) {
      triples.add(`${e.concept}|${e.canonical}|${e.standard_status}`);
    }
  }
  return triples;
}

// --- corpus parsing ----------------------------------------------------------

// Extract M source blocks from a tree-sitter test corpus file. Format:
//   ====================
//   Test name
//   ====================
//
//   <source>
//
//   --------------------
//
//   <expected sexp>
//
// Each source block may also have an attribute line above it (e.g. `:skip`)
// per tree-sitter test format — those are ignored here.
function extractSources(filePath) {
  const text = fs.readFileSync(filePath, 'utf-8');
  const lines = text.split('\n');
  const sources = [];
  let i = 0;
  while (i < lines.length) {
    if (!/^=+$/.test(lines[i])) { i++; continue; }
    // header opener; skip name lines and matching closer
    i++;
    while (i < lines.length && !/^=+$/.test(lines[i])) i++;
    i++;  // past closer
    // collect source until divider
    const srcLines = [];
    while (i < lines.length && !/^-+$/.test(lines[i])) {
      srcLines.push(lines[i]);
      i++;
    }
    // skip divider, sexp, blank
    while (i < lines.length && !/^=+$/.test(lines[i])) i++;
    // strip the leading and trailing blank lines tree-sitter format uses
    while (srcLines.length && srcLines[0] === '') srcLines.shift();
    while (srcLines.length && srcLines[srcLines.length - 1] === '') srcLines.pop();
    if (srcLines.length) sources.push(srcLines.join('\n') + '\n');
  }
  return sources;
}

// --- tree walking ------------------------------------------------------------

const KEYWORD_NODE_TYPES = new Set(Object.keys(stamp.NODE_TYPE_TO_CONCEPT));

function walkKeywords(node, source, out) {
  if (KEYWORD_NODE_TYPES.has(node.type)) {
    const text = source.slice(node.startIndex, node.endIndex);
    const r = stamp.lookup(node.type, text);
    if (r) {
      // Treat ambiguous matches as covering all candidates — per spec
      // §10.3 the gate verifies "at least one corpus test exercises that
      // token", and the form does exercise every candidate's recognition.
      for (const c of r.candidates) {
        out.add(`${r.concept}|${c.canonical}|${c.standard_status}`);
      }
    }
  }
  for (let i = 0; i < node.namedChildCount; i++) {
    walkKeywords(node.namedChild(i), source, out);
  }
}

// --- main --------------------------------------------------------------------

function main() {
  const required = loadRequiredTriples();

  const parser = new Parser();
  parser.setLanguage(M);

  const covered = new Set();
  const corpusFiles = fs.readdirSync(CORPUS_DIR).filter(f => f.endsWith('.txt'));
  let testCount = 0;
  for (const f of corpusFiles) {
    const sources = extractSources(path.join(CORPUS_DIR, f));
    for (const src of sources) {
      const tree = parser.parse(src);
      walkKeywords(tree.rootNode, src, covered);
      testCount++;
    }
  }

  // Plus the synthetic coverage routine generated by
  // tools/build-coverage-corpus.js — one keyword node per pair so the
  // hand-curated structural corpus doesn't have to enumerate all 347.
  let coverageFiles = [];
  if (fs.existsSync(COVERAGE_DIR)) {
    coverageFiles = fs.readdirSync(COVERAGE_DIR).filter(f => f.endsWith('.m'));
    for (const f of coverageFiles) {
      const src = fs.readFileSync(path.join(COVERAGE_DIR, f), 'utf-8');
      const tree = parser.parse(src);
      walkKeywords(tree.rootNode, src, covered);
      testCount++;
    }
  }

  const missing = [...required].filter(t => !covered.has(t)).sort();
  const reportPair = (t) => {
    const [concept, canonical, status] = t.split('|');
    return { concept, canonical, standard_status: status };
  };

  if (asJson) {
    process.stdout.write(JSON.stringify({
      corpus_files: corpusFiles.length,
      corpus_blocks: testCount,
      required_triples: required.size,
      covered_triples: covered.size,
      missing_triples: missing.length,
      missing: missing.map(reportPair),
    }, null, 2) + '\n');
  } else {
    console.log(`coverage gate: ${covered.size} / ${required.size} (concept, canonical, status) triples covered`);
    console.log(`               from ${testCount} blocks across ${corpusFiles.length} corpus + ${coverageFiles.length} coverage file(s)`);
    if (missing.length === 0) {
      console.log(`               PASS — every keyword has at least one corpus test`);
    } else {
      console.log(`\nMISSING (${missing.length}):`);
      const byConcept = {};
      for (const t of missing) {
        const p = reportPair(t);
        (byConcept[p.concept] ||= []).push(p);
      }
      for (const c of Object.keys(byConcept).sort()) {
        console.log(`\n  ${c} (${byConcept[c].length}):`);
        for (const p of byConcept[c]) {
          console.log(`    ${p.canonical.padEnd(20)} ${p.standard_status}`);
        }
      }
      console.log(`\nFAIL — add a corpus test exercising each missing form.`);
    }
  }

  process.exit(missing.length === 0 ? 0 : 1);
}

main();
